# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim
WORKDIR /app
# install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
# Copy entire source code
COPY . .
# Default command (overridden by MCP start wrapper)
CMD ["python", "server.py"]
